version: '3'

services:

  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim

  grout:
    build: ./grout-server
    depends_on:
      - db
    volumes:
      - ./grout-server:/opt/grout-server
    entrypoint: python
    command: manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: ./grout-server/.env

  editor:
    build: ./grout-schema-editor
    depends_on:
      - grout
    volumes:
      - ./grout-schema-editor:/opt/schema_editor
    entrypoint: ./node_modules/parcel-bundler/bin/cli.js
    command: app/index.html --hmr-port 35845
    ports:
      - "1234:1234"
      - "9000:9000"
      - "35845:35845"

  app:
    image: node:9.11.1-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./app:/opt/app
    working_dir: /opt/app
    entrypoint: npm
    command: run dev

  loaddata:
    build: ./scripts/sample_data
    volumes:
      - ./scripts/sample_data:/opt/loaddata
    working_dir: /opt/loaddata
    depends_on:
      - grout
    command: python loaddata.py

  nginx:
    build: ./deployment/nginx
    depends_on:
      - grout
    ports:
      - "80:80"
