version: '3'

services:

  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim

  ashlar:
    build: .
    depends_on:
      - db
    volumes:
      - .:/opt/ashlar-server
    entrypoint: python
    command: manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=0  # Do not buffer output (allows Docker to stream stdout)
