#!/bin/bash

# Most reliable way to get the path for this script.
# h/t: https://stackoverflow.com/questions/192292/bash-how-best-to-include-other-scripts/12694189#12694189
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]];
then
    DIR="$PWD"
fi

# Load common configs for this script.
source "${DIR}/_config.sh"

function usage() {
    echo -n "Usage: $(basename "$0")

Clean up unused Docker resources to free disk space.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Remove unused containers, images, and volumes
        docker system prune -f
    fi
fi
