#!/bin/bash

# Most reliable way to get the path for this script.
# h/t: https://stackoverflow.com/questions/192292/bash-how-best-to-include-other-scripts/12694189#12694189
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]];
then
    DIR="$PWD"
fi

# Load common configs for this script.
source "${DIR}/_config.sh"

# Import DB initialization methods.
source "${DIR}/_init_db.sh"

function usage() {
    echo -n "Usage: $(basename "$0")

Make sure containers and NPM modules are up to date.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Building containers..."
        echo "----------------------------------------------------------"
        docker-compose build
        echo

        echo "Running migrations in the Grout app..."
        echo "----------------------------------------------------------"
        init_db
        docker-compose run --rm grout manage.py migrate
        echo

        echo "Uploading sample data..."
        echo "----------------------------------------------------------"
        docker-compose run --rm loaddata
        echo

        echo "Installing NPM modules in the frontend app..."
        echo "----------------------------------------------------------"
        docker-compose run --rm app install
        echo

        echo "Installing NPM modules in the schema editor backend app..."
        echo "----------------------------------------------------------"
        docker-compose run --rm --entrypoint "yarn install" editor
        echo

        echo "Stopping all running services..."
        echo "----------------------------------------------------------"
        docker-compose stop
        echo

        echo "Build complete!"
    fi
fi
