#!/bin/bash

# Most reliable way to get the path for this script.
# h/t: https://stackoverflow.com/questions/192292/bash-how-best-to-include-other-scripts/12694189#12694189
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]];
then
    DIR="$PWD"
fi

# Load common configs for this script.
source "${DIR}/_config.sh"

# Import DB initialization methods.
source "${DIR}/_init_db.sh"

function usage() {
    echo -n "Usage: $(basename "$0")

Make sure containers and NPM modules are up to date.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build containers.
        docker-compose build

        # Run migrations.
        init_db
        docker-compose run --rm grout manage.py migrate

        # Upload sample data.
        docker-compose run --rm loaddata

        # Install NPM modules.
        docker-compose run --rm app install

        # Stop all services.
        docker-compose stop
    fi
fi
